<a href="https://colab.research.google.com/github/wtfashwin/Python-/blob/main/Modules_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Module :
a single file is called as module

##Package
multiple modules combined makes a package

##Library
many packages make a library

arr - time efficient

list comparitively slower than array

#NumPy
(Numerical Python) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [ ]:
import numpy as np
#np is called as alias , we'd use use np to use numpy

arr = np.array([1, 2, 3, 4, 5])

arr2 = np.array(([1, 2, 3, 4],[4,9,6,7]))
#all elements should be ideal,

print("NumPy array:", arr)
print(arr2)

NumPy array: [1 2 3 4 5]
[[1 2 3 4]
 [4 9 6 7]]


In [ ]:
arrzero = np.ones(4)
print(arrzero)

[1. 1. 1. 1.]


#Attributes

 - np.ndim
 - ndarray.shape
 - reshape
 - size
 - itemsize
 - dtype

In [ ]:
#Using ndim

arr = np.array([[1,2,3], [5,6,7], [8,9,10]])
#here we declared 2D arr
print(arr)
print(arr.ndim)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
2


In [ ]:
arr = np.array([[1,2,3], [5,6,7], [8,9,10], [11,12,13]])
print(arr)
print(arr.shape)
#gives shape of array
#first value gives rows(4) , second gives column(3)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
(4, 3)


In [ ]:
arr3 = np.array([(1,2,3), (4,5,6)])
print(arr3)
print(arr3.reshape)

[[1 2 3]
 [4 5 6]]
<built-in method reshape of numpy.ndarray object at 0x7f7581cef1b0>


In [ ]:
arr4 = np.array([1,2,3,4,5,6])
reshaped = arr3.reshape(2,3)
print(reshaped)



[[1 2 3]
 [4 5 6]]


In [ ]:
arr4 = np.array([1,2,3,4,5,6])

print(arr4.size) # Number of elements in the array
print(arr4.itemsize) # Size of each element in bytes
print(arr4.dtype) # Data type of the elements

6
8
int64


##Accessing elements from array

In [ ]:
arr4 = np.array([1,2,3,4,5,6])
print(arr4[3])
print(arr4[2] + arr4[4])

4
8


In [ ]:
arr4 = np.array([[1,2,3],[4,5,6]])
print(arr4[0][1])
print(arr4[1,1])

2
5


In [ ]:
arr5 = np.array([1,2,3,4,5,6])
print(arr5[1:5])

[2 3 4 5]


In [ ]:
#inbuilt function
#min, max

print(arr5.min())
print(arr5.max())

1
6


In [ ]:
# Standard Deviation

#value close to mean - good for data

#value are spread out - not good
np.std(arr5)

np.float64(1.707825127659933)

In [ ]:
#sqrt
arr6 = np.array([1,2,3,4,5,6])

np.sqrt(arr6)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
#flattern - converts multidimensional array in single dimensional arr
#2D to 1D arr

arr7 = np.array([[1,2,3],[4,5,6]])
print(arr7.flatten())

[1 2 3 4 5 6]


In [ ]:
#transpose - converting rows - columns & viceversa

arr8 = np.array([[1,2,3],[4,5,6]])
print(arr8)
print(arr8.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Concatenate - multiple arr in one

arr9 = np.array([1,2,3])
arr10 = np.array([4,5,6])
print(np.concatenate([arr9, arr10]))

[1 2 3 4 5 6]


In [ ]:
#Split - mostly used, splits arr in equal parts

arr = np.array([10,20,30,60,70,80])
print(np.split(arr, 3))

[array([10, 20]), array([30, 60]), array([70, 80])]


In [ ]:
#comparison operations

arr = np.array([10,20,30,60,70,80])
print(arr>20)

[False False  True  True  True  True]


In [ ]:
#Filter or condition apply
print(np.where(arr>20,'High', 'Low'))

['Low' 'Low' 'High' 'High' 'High' 'High']


In [ ]:
#Modules
#if we want to generate random numbers
#numbers generated are float

np.random.rand(3)

array([0.31040358, 0.46210827, 0.88327092])

In [ ]:
# np.random.randint(start ,stop, size=)
np.random.randint(1,100,size=4)

array([33, 13, 51, 29])